[package]
name = "temperature-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "*"
anyhow = { version = "*", features = ["backtrace"] }
chrono = "*"
temperature-protocol = { path = "../../protocol" }
tokio = { version = "1.36"}

