[package]
name = "temperature-server"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "*"
anyhow = { version = "*", features = ["backtrace"] }
chrono = "*"
temperature-protocol = { path = "../../protocol" }
history = { path = "../../history" }
axum = { version = "*", features = ["ws", "macros"] }
tokio = { version = "*", features = ["full"] }
tower-http = { version = "*", features = ["fs", "compression-full"] }
tower = "*"
futures = "*"
futures-util = { version = "0.3", features = ["sink"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"

