[package]
name = "temperature-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
protobuf = "*"
anyhow = { version = "*", features = ["backtrace"] }
chrono = "*"
tokio = { version = "*", features = ["net", "rt", "sync"] }

[build-dependencies]
protobuf-codegen = "*"
